### ISSUE TITLE
Downgraded Dektrium user due to update to v 3.3.0

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/yii2-cms-metapackage#2]
There is new version of user module 0.9.6., but metapackage updated to version 3.3.0 downgrades user module to version 0.9.5. Is there any problem with compatibility? 
https://packagist.org/packages/dmstr/yii2-cms-metapackage#3.3.0
https://github.com/dmstr/yii2-cms-metapackage/commit/b1f441cad6ce86e7cf52eced7a0562426f71b086

**Comment by schmunk42** [comment]
Yes, we ran into a recursion error with the default Phundament template, see https://github.com/phundament/app/commit/8d432331332b44ebbb2ec49fdfcd6806dd3aff51

I created a 4.0.0-beta1 package, but merely because of `dmstr/yii2-pages-module`, I plan to create a stable version of this repo in the next days.

You can either give `4.0.0-beta1` a try, if you i.e. don't use pages. 
Or add an alias for `"dektrium/yii2-user": "0.9.6 as 0.9.5.999"` to upgrade just this package.

**Comment by akaSStalkALEX** [comment]
Sorry for disturbing, I commented pages module in main config, also required `4.0.0-beta1` in composer, but there is `pages` item in backend among the modules, it boostrrapped anyway somewhere else. I tried to find by myself but failed. Maybe small hint?

**Comment by StalkAlex** [comment]
Maybe this question is inappropriate but I ask if there is any way to choose extensions which will be loaded/bootstraped in this extension? If I don't need pages, for example, it boostrapped automatically even if it is commented in main config because of yii auto - bootstrapping extensions from vendor folder.

**Comment by schmunk42** [comment]
It's an absolutely valid question :)

But disabling the extension should be done here: https://github.com/dmstr/yii2-pages-module/blob/master/Bootstrap.php

Maybe we could just add migrations and URL rules if the extension is configured manually. CC: @Quexer69 Any thoughts? - but the extension should not be loaded unless used in a request.

Another workaround for you would be to pick just the extension you need from here, basically copy & paste - also not ideal.

**Comment by StalkAlex** [comment]
Yeah, I also thought that copy-paste is bad practice. I can help you to test/implement something. There is `extension` param in config, might be helpful somehow.
http://www.yiiframework.com/doc-2.0/yii-base-application.html#$extensions-detail

**Comment by akaSStalkALEX** [comment]
There is no bootstrap.php config in Phundament, isn't there? 
https://github.com/yiisoft/yii2/issues/11236#issuecomment-203786216
